version: "3.3"

services:
  app:
    container_name: base-server
    build:
      context: ./
      dockerfile: ./Dockerfile
    working_dir: /home/node/app
    command: [ "npm", "run", "start:dev" ]
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    volumes:
      - ./:/home/node/app
    ports:
      - ${PORT}:${PORT}
    networks:
      - base-network
    depends_on:
      - redis

  redis:
    container_name: base-redis
    image: redis/redis-stack-server:latest
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis:/data
    networks:
      - base-network

volumes:
  redis:
    driver: local

networks:
  base-network:
    driver: bridge